config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|es/ do
    root 'sessions#new'

    get 'registro', to: 'users#new'
    get 'usuarios', to: 'users#index'
    
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    get 'logout', to: 'sessions#destroy'

    get 'soporte', to: 'tickets#support'
    get 'cliente', to: 'tickets#customer'
    get 'adminticket',  to: 'tickets#admin'
    get 'tickets', to: 'tickets#index'
    get 'ingresoticket', to: 'tickets#new'
    
    get 'administracion', to: 'pages#adminpanel'
    get 'contacto', to: 'pages#contact'
    get 'soporte', to: 'pages#support'

    resources :tickets
    resources :users
    resources :tickets do
      resources :replies
    end

    resources :account_activations, only: [:edit]
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	belongs_to :user
	has_many :replies

	validates :user_id, presence: true
	validates :title, presence: true, length: { minimum: 3, maximum: 35 }
	validates :description, presence: true, length: { minimum: 3, maximum: 500 }
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
	before_action :set_ticket, only: [:show, :edit, :update, :destroy]
	before_action :support_name, only: [:customer, :admin, :show]

	# GET /tickets
	def index
		redirect_according_account
	end

	def support
		@tickets = Ticket.where(["support = ? OR status = ?",current_user.id, "En Espera"])
	end

	def customer
		@tickets = current_user.tickets
	end

	def admin
		@tickets = Ticket.all
	end

	# GET /tickets/1
	def show
		@customer = User.select("name").where(id: @ticket.user_id).take
	end

	# GET /tickets/new
	def new
		@ticket = Ticket.new
		if is_support || is_admin
			@customers = User.select(:id, :name, :email).where(account: "C")
		else
			@ticket.user_id = current_user
		end
	end

	# GET /tickets/1/edit
	def edit
	end

	# POST /tickets
	def create
		@ticket = Ticket.new(ticket_params)
		@ticket.user_id = current_user.id
		if @ticket.save
			flash[:success] = t('.flashcreated')
			#UserMailer.ticket_ingresado(@ticket).deliver_now
			redirect_to @ticket
		else
			
			flash[:danger] = "error"
		 	render :new 
		end
	end

	# PATCH/PUT /tickets/1
	def update
		if @ticket.update(ticket_params)
			flash[:success] = t('.flashupdated')
			redirect_to @ticket 
		else
			render :edit
		end
	end

	# DELETE /tickets/1
	def destroy
		@ticket.destroy
		flash[:success] = t('.flashdeleted')
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_ticket
			@ticket = Ticket.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def ticket_params
			params.require(:ticket).permit(:title, :description, :status)
		end

		def support_name
			@support = User.select(:id, :name).where(account: "S")
		end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for @ticket, html: {class: "form-horizontal"} do |f| %>
	<% if is_admin || is_support %>

		<div class="form-group ">
			<%= f.label t('.inputuser'), class: "col-sm-2 control-label" %>
			<div class="col-sm-6">
				<span id="helpBlock2" class="help-block">Seleccione el cliente para el cual se está creando este ticket.</span>
				<%= f.select :user_id, options_for_select(@customers.map{ |c| [c.name+" <"+c.email+">", c.id] }),{}, { class: "form-control" } %>
			</div>
		</div>
	<% end %>
 
 
  <div class="form-group">
    <%= f.label t('.inputtitle'), class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      	<%= f.text_field :title, class: "form-control", placeholder: t('.placeholdertitle') %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label t('.inputdesc'), class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= f.text_area :description, class: "form-control", size: "3", placeholder: t('.placeholderdesc')  %>
    </div>
  </div>
	
	<%= f.submit t('.inputbutton'), class: "btn btn-success col-md-offset-2" %>
<% end %>

app/views/tickets/_ticketpending.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">Tickets sin responder:</h3>
	</div>
	<table class="table table-hover table-condensed">
		<thead>
			<tr>
				<th style="width: 8%">Folio</th>
				<% if !is_customer %>
				<th style="width: 15%">Usuario</th>
				<% end %>
				<th style="width: 18%">Titulo</th>
				<th style="width: 25%">Descripcion</th>
				<th style="width: 12%">Creado</th>
				<th style="width: 12%">Actualizado</th>
				<th style="width: 10%">Estado</th>
			</tr>
		</thead>
		<tbody>
			<% @tickets.where(status: "En Espera").each do |ticket| %>
			<tr>
				<td><%=link_to ticket.id, ticket %></td>
				<% if !is_customer %>
				<td><%= ticket.user.name %></td>
				<% end %>
				<td><%= ticket.title %></td>
				<td><%= ticket.description.truncate(35)%></td>
				<td><%= ticket.created_at.strftime("%d-%m-%y %H:%M") %></td>
				<td><%= ticket.updated_at.strftime("%d-%m-%y %H:%M") %></td>
				<td><%= ticket.status %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/tickets/admin.html.erb
<% content_for(:page_header) do %><%= t('.adminpage')%><% end %>
<% content_for :panel_heading do %>Content<% end %>

<p id="notice"><%= notice %></p>
<%# render 'ticketpending' %>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-support fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge"> Tickets Respondidos</div>
						<div> asd </div>
					</div>
				</div>
			</div>
			<div class="panel-body">
				<table id="tickets" class="display table" cellspacing="0" width="100%">
					<thead>
						<tr>
							<th>Folio</th>
							<th>Usuario</th>
							<th>Tecnico</th>
							<th>Titulo</th>
							<th>Creado</th>
							<th>Actualizado</th>
						</tr>
					</thead>
					<tbody>
						<% if @tickets %>
							<% @tickets.where.not(status: "En Espera").each do |ticket| %>
							<tr>
								<td><%=link_to ticket.id, ticket %></td>
								<td><%= ticket.user.name %></td>
								<td><%= @support.find_by(id: ticket.support).name %></td>
								<td><%= ticket.title %></td>
								<td><%= ticket.created_at.strftime("%d-%m-%y %H:%M") %></td>
								<td><%= ticket.updated_at.strftime("%d-%m-%y %H:%M") %></td>
							</tr>
							<% end %>
						<%else %>
							"sin tickets"
						<%end%>
					</tbody>
				</table>
			</div>
			<div class="panel-footer">
			</div>
		</div>
	</div>
</div>

<% content_for(:extra_scripts) do %>
	<script type="text/javascript">
		$(document).ready(function() {
			$('#tickets').DataTable({ responsive: true });
		});
	</script>
<% end %>

app/views/tickets/customer.html.erb
<div class="jumbotron">
	<h1> Tickets</h1>
	<div class="panel panel-primary">
		<div class="panel-heading">
    	<h3 class="panel-title">Tickets Respondidos:</h3>
  	</div>
		<table class="table table-hover table-condensed">
			<thead>
				<tr>
					<th style="width: 8%">Folio</th>
					<th style="width: 15%">Encargado</th>
					<th style="width: 30%">Titulo</th>
					<th style="width: 15%">Creado</th>
					<th style="width: 15%">Actualizado</th>
					<th style="width: 12%">Estado</th>
				</tr>
			</thead>
			<tbody>
				<% @tickets.where.not(status: "En Espera").each do |ticket| %>
					<tr>
						<td><%=link_to ticket.id, ticket %></td>
						<td><%= @support.find_by(id: ticket.support).name %></td>
						<td><%= ticket.title %></td>
						<td><%= ticket.created_at.strftime("%d-%m-%y %H:%M") %></td>
						<td><%= ticket.updated_at.strftime("%d-%m-%y %H:%M") %></td>
						<td><%= ticket.status %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<%= render 'ticketpending' %>
</div>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/new.html.erb
<% provide(:title, ' registro ') %>

<div class="row">
		<div class="col-md-12">
			<div class="panel panel-primary">
				<div class="panel-heading">
						<div class="row">
								<div class="col-xs-3">
									<i class="fa fa-support fa-5x"></i>
								</div>
								<div class="col-xs-9 text-right">
										<div class="huge"><%= t('.title') %></div>
										<div>asd</div>
								</div>
						</div>
				</div>
				<div class="panel-body">
					<%= render 'form' %>
				</div>
				<div class="panel-footer">
				</div>
			</div>
		</div>
</div>

app/views/tickets/show.html.erb
<% content_for(:page_header) do %><%= t('.showticket')%><% end %>
<% content_for :panel_heading do %>showticket<% end %>

<p id="notice"><%= notice %></p>

<div class="panel panel-default ">
	<div class="panel-heading">
		<h3 class="panel-title ">Ticket Folio #<%=@ticket.id%> </h3>
			<% if is_support || is_admin || is_customer %>
				<% if @ticket.status == "En Espera" %>
				  <%= form_for @ticket do |t| %>
				    <%= t.hidden_field :status, :value => "En Proceso"%>
				    <%= t.hidden_field :support, :value => current_user.id %>
				    <%= t.submit "Aceptar Ticket", class: "btn btn-xs btn-success" %>
				  <% end %>
				<% end %>

				<% if @ticket.status == "Cerrado" %>
				  <%= form_for @ticket do |t| %>
				    <%= t.hidden_field :status, :value=>"En Proceso"%>
				    <%= t.hidden_field :support, :value => current_user.id %>
				    <%= t.submit "Reabrir Ticket", class: "btn btn-xs btn-info" %>
				  <% end %>
				<% end %>

				<% if @ticket.status != "Cerrado" %>
			  	<%= form_for @ticket do |t| %>
					  <%= t.hidden_field :status, :value=>"Cerrado"%>
					  <%= t.submit "Cerrar Ticket", class: "btn btn-xs btn-danger" %>
					<% end %>
				<% end %>

				<% if @ticket.status == "En Espera" %>
					<%= link_to "Editar Ticket", edit_ticket_path(@ticket), class: "btn btn-xs btn-primary" %>
				<% end %>
			<% end %>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-list-alt fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge">Ticket</div>
						<div>Folio #<%= @ticket.id %></div>
					</div>
				</div>
			</div>
			<div class="panel-body ">
					<dl class="dl-horizontal ">
					  <dt>Soporte</dt>	<dd><%= @support.find_by(id: @ticket.support).name if @ticket.support %></dd>
						<dt>Fecha creacion</dt>	<dd><%= @ticket.created_at.strftime("%d-%m-%y %H:%M") %></dd>
						<dt>Ultima actualizacion</dt>	<dd><%= @ticket.updated_at.strftime("%d-%m-%y %H:%M") %></dd>
						<dt>Estado</dt>	<dd><%= @ticket.status %></dd>
						<dt>Titulo</dt>	<dd><%= @ticket.title %></dd>
						<dt>Descripcion</dt>	<dd><%= @ticket.description %></dd>
					</dl>
					<%= link_to t('.userupdate'), '#' , class: "btn btn-success col-md-offset-2" %>
			</div>
			<div class="panel-footer">
				<%= link_to '<span class="pull-left">'.html_safe+t('.userupdate')+'</span>
				<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
				<div class="clearfix"></div>'.html_safe,
				'#'%>
			</div>
		</div>
	</div>

	<div class="col-md-12">
		<div class="chat-panel panel panel-primary">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-comments fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge">Ticket</div>
						<div>Folio #<%= @ticket.id %></div>
					</div>
				</div>
			</div>
			<div class="panel-body ">
				<% @ticket.replies.each do |reply| %>
					<ul class="chat">
						<% if reply.user.account == 'C' %>
							<li class="left clearfix">
						    <span class="chat-img pull-left">
						      <i class="fa fa-user-circle fa-3x"></i>
						    </span>
						    <div class="chat-body clearfix">
					        <div class="header">
					          <strong class="primary-font"><%= reply.user.name %></strong>
					          <small class="text-muted"><i class="fa fa-clock-o"></i>  <%= reply.updated_at.strftime("%d-%m-%y %H:%M") %></small>
					        </div>
						      <p><%= reply.description %></p>
						    </div>
							</li>
						<% else %>
						  <li class="right clearfix">
					      <span class="chat-img pull-right">
										  <i class="fa fa-support fa-3x text-danger"></i>
					      </span>
					      <div class="chat-body clearfix">
					        <div class="header">
					          <small class=" text-muted"><i class="fa fa-clock-o fa-fw"></i></i> <%= reply.updated_at.strftime("%d-%m-%y %H:%M") %></small>
					          <strong class="pull-right primary-font"><%= reply.user.name %></strong>
					        </div>
					        <p><%= reply.description %></p>
					      </div>
						  </li>
						<% end %>
					</ul>
				<% end %>
			</div>
				<div class="panel-footer">
					<% if @ticket.status != "Cerrado" %>
						<%= form_for([@ticket, @ticket.replies.build] ) do |f| %>
							<div class="input-group">
								<%= f.text_area :description, class: "form-control", size: "3", placeholder: t('.Typeyourmessagehere...') %>
                <span class="input-group-btn">
									<%= f.submit "Agregar Comentario", class: "btn btn-success", id: "btn-chat" %> 
                </span>
              </div>
						<% end %>
					<% end %>
				</div>
			</div>
		</div>
	</div>

app/views/tickets/support.html.erb
<div class="jumbotron">
	<h1> Tickets</h1>
	<div class="panel panel-primary">
		<div class="panel-heading">
    	<h3 class="panel-title">Tickets Respondidos:</h3>
  	</div>
		<table class="table table-hover table-condensed">
			<thead>
				<tr>
					<th style="width: 8%">Folio</th>
					<th style="width: 15%">Usuario</th>
					<th style="width: 18%">Titulo</th>
					<th style="width: 25%">Descripcion</th>
					<th style="width: 12%">Creado</th>
					<th style="width: 12%">Actualizado</th>
					<th style="width: 10%">Estado</th>
				</tr>
			</thead>
			<tbody>
				<% @tickets.where.not(status: "En Espera").each do |ticket| %>
					<tr>
						<td><%=link_to ticket.id, ticket %></td>
						<td><%= ticket.user.name %></td>
						<td><%= ticket.title %></td>
						<td><%= ticket.description.truncate(35)%></td>
						<td><%= ticket.created_at.strftime("%d-%m-%y %H:%M") %></td>
						<td><%= ticket.updated_at.strftime("%d-%m-%y %H:%M") %></td>
						<td><%= ticket.status %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<%= render 'ticketpending' %>
</div>