config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|es/ do
    root 'sessions#new'

    get 'registro', to: 'users#new'
    get 'usuarios', to: 'users#index'
    
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    get 'logout', to: 'sessions#destroy'

    get 'soporte', to: 'tickets#support'
    get 'cliente', to: 'tickets#customer'
    get 'adminticket',  to: 'tickets#admin'
    get 'tickets', to: 'tickets#index'
    get 'ingresoticket', to: 'tickets#new'
    
    get 'administracion', to: 'pages#adminpanel'
    get 'contacto', to: 'pages#contact'
    get 'soporte', to: 'pages#support'

    resources :tickets
    resources :users
    resources :tickets do
      resources :replies
    end

    resources :account_activations, only: [:edit]
  end
end

app/views/layouts/OLD_menu.html.erb
<% if logged_in? %>
	<li class="dropdown active">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name+" ("+current_user.email+")" %> <span class="caret"></span></a>
		<ul class="dropdown-menu">
			<li><%= link_to t('.ticketlist'), tickets_path %></li>
			<li><%= link_to t('.ticketnew'), ingresoticket_path %></li>
		<%if is_admin %>
			<li role="separator" class="divider"></li>
			<li><%= link_to t('.userlist'), usuarios_path %></li>
			<li><%= link_to t('.usernew'), registro_path %></li>
		<% elsif is_support %>
			<li role="separator" class="divider"></li>
			<li><%= link_to t('.usernew'), registro_path %></li>			
		<% end %>
			<li role="separator" class="divider"></li>
			<li><%= link_to t('.profile'), edit_user_path(current_user) %></li>
			<li role="separator" class="divider"></li>
			<li><%= link_to t('.logout'), logout_path %></li>
		</ul>
	</li>
<% else %>
	
	<li class="active"><%= link_to t('.login'), login_path %></li>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<%= link_to "Ticket 2017", root_path %>
	</small>
	<nav>
		<ul>
			<li><%= link_to "Registro", registro_path %></li>
			<li><%= link_to "Iniciar Sesion", login_path %></li>
			<li><%= link_to "Cerrar Sesion", logout_path %></li>
			<li><%= link_to "Admin", administracion_path %></li>
			<li><%= link_to "soporte", soporte_path %></li>
			<li><%= link_to "cliente", cliente_path %></li>
			<li><%= link_to "Contacto", contacto_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message| %>
	<div class="modal " id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog">
	    <div class="modal-body alert alert-<%= message_type %>">
	    	<i class="fa fa-info-circle fa-fw "></i><%= message %>
	    	<button type="button" class="btn btn-<%= message_type %> " data-dismiss="modal"  data-target="#myModal">Close</button>
	    </div>
	  </div>
	</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top " role="navigation" style="margin-bottom: 0">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse">
			<span class="sr-only">Toggle navigation</span>
    		<span class="icon-bar"></span>
          	<span class="icon-bar"></span>
              <span class="icon-bar"></span>
		</button>
		<%= link_to "Ticket", root_path, class: "navbar-brand" %>
	</div>
	<ul class="nav navbar-top-links navbar-right ">
		<% if params[:locale] == 'es' %> 
		<li><%= link_to url_for( :locale => 'en' ) do %> <span class="fa fa-language fa-fw fa-lg"></span>ES<% end %></li>
		<% else %>
		<li><%= link_to url_for( :locale => 'es' ) do %> <span class="fa fa-language fa-fw fa-lg"></span>EN<% end %></li>
		<% end %>
		<% if logged_in? %>
		<li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
			<ul class="dropdown-menu dropdown-alerts">
	            <li><a href="#"><div><i class="fa fa-comment fa-fw"></i>Ticket #2356 New Reply<span class="pull-right text-muted small">4 minutes ago</span></div></a></li>
	            <li class="divider"></li>
	            <li><a href="#"><div><i class="fa fa-twitter fa-fw"></i> Ticket #2356 New Reply<span class="pull-right text-muted small">12 minutes ago</span></div></a></li>
	        </ul>
	    </li>
	    <li class="dropdown">
	    	<a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
			<ul class="dropdown-menu dropdown-user">
				<li><%= link_to '<i class="fa fa-id-card fa-fw"></i>Profile'.html_safe, user_path(current_user) %></li>
				<li class="divider"></li>
				<li><%= link_to '<i class="fa fa-sign-out fa-fw"></i>Logout'.html_safe, logout_path %></li>
			</ul>
		</li>
	</ul>
	<!-- navbar sidebar -->
	<%= render 'layouts/sidebar' %>
	<% else %>
	<li><%= link_to '<i class="fa fa-sign-in fa-fw fa-lg"></i>'.html_safe+t('.login'), login_path %></li> 
</ul>
<% end %>
</nav>

app/views/layouts/_sidebar.html.erb
	<div class="navbar-default sidebar " role="navigation">
		<div class="sidebar-nav navbar-collapse">
			<ul class="nav in" id="side-menu">
				<li><%= link_to '<i class="fa fa-dashboard fa-fw"></i>'.html_safe+t('.dashboard'), root_path %></li>
				<% if is_admin %>
					<li><%= link_to '<i class="fa fa-dashboard fa-fw"></i>'.html_safe+t('.userlist'), usuarios_path %></li> 
					<li><%= link_to '<i class="fa fa-dashboard fa-fw"></i>'.html_safe+t('.usernew'), registro_path %></li>  
				<% end %>

					<li><%= link_to '<i class="fa fa-list fa-fw"></i>'.html_safe+t('.ticketlist'), tickets_path %></li>      
					<li><%= link_to '<i class="fa fa-ticket fa-fw"></i>'.html_safe+t('.ticketnew'), ingresoticket_path %></li> 
					<li><%= link_to '<i class="fa fa-dashboard fa-fw"></i>'.html_safe+t('.profile'), edit_user_path(current_user) %></li>  
					<li><%= link_to '<i class="fa fa-phone fa-fw"></i>'.html_safe+t('.contactus'), contacto_path %></li>
			</ul>
		</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="google" content="notranslate">
<meta http-equiv="Content-Language" content="en">
  <title>
    <%= content_for?(:title) ? yield(:title) : "Ticket" %>
  </title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if logged_in? %>
    <div id="wrapper">
      <%= render 'layouts/navbar' %>
    </div>
    <div id="page-wrapper">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  <% else %>
    <div id="wrapper">
      <%= render 'layouts/navbar' %>
    </div>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  <% end %>
</body>
<%# render 'layouts/footer' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= content_for?(:extra_scripts) ? yield(:extra_scripts) : nil %>
</html>